module MotorControllerUnitModule
{
  struct ControlCommandMessage
  {
    string command;
  };
  #pragma keylist ControlCommandMessage

  struct MotorResponseMessage
  {
    string response;
  };
  #pragma keylist MotorResponseMessage

  struct MotorOutputMessage
  {
    float ftCurrentU;
    float ftCurrentV;
    float ftCurrentW;
    float ftRotorRPM;
    float ftRotorDegreeRad;
    float ftOutputTorque;
  };
  #pragma keylist MotorOutputMessage

  struct NodejsRequestMessage
  {
    string request;
  };
  #pragma keylist NodejsRequestMessage
};
