module MotorControllerUnitModule
{
  struct ControlMessage
  {
    string content;
  };
  #pragma keylist ControlMessage

  struct MotorMessage
  {
    string content;
  };
  #pragma keylist MotorMessage

  struct MotorOutputMessage
  {
    float ftCurrentU;
    float ftCurrentV;
    float ftCurrentW;
    float ftRotorRPM;
    float ftRotorDegreeRad;
    float ftOutputTorque;
  };
  #pragma keylist MotorOutputMessage
};
