module MotorControllerUnitModule
{
  struct ControlMessage
  {
    string content;
  };
  #pragma keylist ControlMessage

  struct MotorMessage
  {
    string content;
  };
  #pragma keylist MotorMessage
};
