module MotorControllerUnitModule
{
  struct ControlMessage
  {
    long id;
    string content;
  };
  #pragma keylist ControlMessage id

  struct MotorMessage
  {
    long id;
    string content;
  };
  #pragma keylist MotorMessage id
};