// Copyright 2011 National Instruments
// License: NATIONAL INSTRUMENTS SOFTWARE LICENSE AGREEMENT
//   Refer to "MHDDK License Agreement.pdf" in the root of this distribution.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___tBusInterface_h___
#include "tBusInterface.h"
#endif

tBusInterface::tBusInterface(tBusSpaceReference addrSpace, nMDBG::tStatus2* s)

{
   _addressOffset = 0;
   _addrSpace = addrSpace;

   _initialize(s);
}

tBusInterface::tBusInterface()

{
   _addressOffset = 0;

}

void tBusInterface::initialize(tBusSpaceReference addrSpace, u32 addressOffset, nMDBG::tStatus2* s)
{

   _addrSpace = addrSpace;
   _addressOffset = addressOffset;

   _initialize(s);
}

void tBusInterface::reset(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

   GlobalInterruptStatus_Register.setRegister(u16(0x0), s);
   AI_Interrupt_Status_Register.setRegister(u16(0x0), s);
   AO_Interrupt_Status_Register.setRegister(u16(0x0), s);
   unsigned int i;
   for(i = 0; i < 4; ++i) {
      TIO_Interrupt_Status_Register[i].setRegister(u16(0x0), s);
   }
   DI_Interrupt_Status_Register.setRegister(u16(0x0), s);
   DO_Interrupt_Status_Register.setRegister(u16(0x0), s);
   Gen_Interrupt_Status_Register.setRegister(u16(0x0), s);
}

void tBusInterface::_initialize(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

   {
      unsigned int i;
      for (i=0; i<4; ++i) {
         TIO_Interrupt_Status_Register[i].initialize(0x76 + (0x2 * i), 0x3 + i);
      }
   }


   //----------------------------------------
   // set register maps of all registers
   //----------------------------------------
   GlobalInterruptStatus_Register.setRegisterMap(this);
   AI_Interrupt_Status_Register.setRegisterMap(this);
   AO_Interrupt_Status_Register.setRegisterMap(this);
   {
      unsigned int i;
      for(i = 0; i < 4; ++i) {
         TIO_Interrupt_Status_Register[i].setRegisterMap(this);
      }
   }
   GlobalInterruptEnable_Register.setRegisterMap(this);
   DI_Interrupt_Status_Register.setRegisterMap(this);
   DO_Interrupt_Status_Register.setRegisterMap(this);
   Gen_Interrupt_Status_Register.setRegisterMap(this);

   //----------------------------------------
   // initialize dirty flags
   //----------------------------------------
   for (unsigned int i = 0; i < sizeof(_dirtyVector)/sizeof(_dirtyVector[0]); i++) {
      _dirtyVector[i] = 0;
   }

   //----------------------------------------
   // reset registers
   //----------------------------------------
   reset(s);
}

tBusInterface::~tBusInterface()
{
}



// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

