// Copyright 2011 National Instruments
// License: NATIONAL INSTRUMENTS SOFTWARE LICENSE AGREEMENT
//   Refer to "MHDDK License Agreement.pdf" in the root of this distribution.

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef ___tOutTimer_h___
#include "tOutTimer.h"
#endif

tOutTimer::tOutTimer(tBusSpaceReference addrSpace, nMDBG::tStatus2* s)

{
   _addressOffset = 0;
   _addrSpace = addrSpace;

   _initialize(s);
}

tOutTimer::tOutTimer()

{
   _addressOffset = 0;

}

void tOutTimer::initialize(tBusSpaceReference addrSpace, u32 addressOffset, nMDBG::tStatus2* s)
{

   _addrSpace = addrSpace;
   _addressOffset = addressOffset;

   _initialize(s);
}

void tOutTimer::reset(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;

   Status_1_Register.setRegister(u32(0x0), s);
   UI_Load_A_Register.setRegister(u32(0x0), s);
   UI_Load_A_Register.markDirty(s);
   UI_Save_Register.setRegister(u32(0x0), s);
   UI_Load_B_Register.setRegister(u32(0x0), s);
   UI_Load_B_Register.markDirty(s);
   UC_Load_A_Register.setRegister(u32(0x0), s);
   UC_Load_A_Register.markDirty(s);
   UC_Save_Register.setRegister(u32(0x0), s);
   UC_Load_B_Register.setRegister(u32(0x0), s);
   UC_Load_B_Register.markDirty(s);
   BC_Load_A_Register.setRegister(u32(0x0), s);
   BC_Load_A_Register.markDirty(s);
   BC_Save_Register.setRegister(u32(0x0), s);
   BC_Load_B_Register.setRegister(u32(0x0), s);
   BC_Load_B_Register.markDirty(s);
   Mode_1_Register.setRegister(u32(0x0), s);
   Mode_1_Register.markDirty(s);
   Mode_2_Register.setRegister(u32(0x0), s);
   Mode_2_Register.markDirty(s);
   Output_Control_Register.setRegister(0x1, s);
   Output_Control_Register.markDirty(s);
}

void tOutTimer::_initialize(nMDBG::tStatus2* s)
{
   if (s && s->isFatal()) return;



   //----------------------------------------
   // set register maps of all registers
   //----------------------------------------
   Command_1_Register.setRegisterMap(this);
   Status_1_Register.setRegisterMap(this);
   UI_Load_A_Register.setRegisterMap(this);
   UI_Save_Register.setRegisterMap(this);
   UI_Load_B_Register.setRegisterMap(this);
   UC_Load_A_Register.setRegisterMap(this);
   UC_Save_Register.setRegisterMap(this);
   UC_Load_B_Register.setRegisterMap(this);
   BC_Load_A_Register.setRegisterMap(this);
   BC_Save_Register.setRegisterMap(this);
   BC_Load_B_Register.setRegisterMap(this);
   Mode_1_Register.setRegisterMap(this);
   Mode_2_Register.setRegisterMap(this);
   Output_Control_Register.setRegisterMap(this);
   Interrupt1_Register.setRegisterMap(this);
   Interrupt2_Register.setRegisterMap(this);
   Reset_Register.setRegisterMap(this);

   //----------------------------------------
   // initialize dirty flags
   //----------------------------------------
   for (unsigned int i = 0; i < sizeof(_dirtyVector)/sizeof(_dirtyVector[0]); i++) {
      _dirtyVector[i] = 0;
   }

   //----------------------------------------
   // reset registers
   //----------------------------------------
   reset(s);
}

tOutTimer::~tOutTimer()
{
}



// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This file is autogenerated!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

