non_precision_resistor_controller: non_precision_resistor_controller_main.cpp
	g++ non_precision_resistor_controller_main.cpp -o non_precision_resistor_controller \
			-L/usr/local/lib64 -lpilpxi64 -Wl,-rpath /usr/local/lib

clean:
	rm -f non_precision_resistor_controller
